name: Release

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build jar
        run: chmod +x ./gradlew && ./gradlew clean build
      - name: Run tests
        run: ./gradlew test
      - name: Build the Docker image
        run: docker build -t lhamacorp/anoning .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push lhamacorp/applicants