name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build jar
        run: chmod +x ./gradlew && ./gradlew clean build
      - name: Run tests
        run: ./gradlew test